
- name: Configure PHP-FPM
  template:
    src: www.conf.jinja2
    dest: /etc/php-fpm.d/www.conf

- name: Support PHP
  copy:
    src: php.conf.jinja2
    dest: /etc/nginx/extra/php.conf
  when: nginx
  
  - name: Support PHP
  copy:
    src: php.conf.jinja2
    dest: /etc/httpd/conf.d/php.conf
  when: apache
