- name:  get the running server | apche | nginx |nothing
  shell: |
    if [ `ps -ef | grep nginx | grep -v grep | wc -l` -gt 0 ];then
    php_run_server=nginx
    elif [ `ps -ef | grep apache | grep -v grep | wc -l` -gt 0 ];then
    php_run_server=apache
    else
    php_run_server=nothing
    fi
    echo $php_run_server
  register: php_run_server

- debug: var=php_run_server.stdout

- name: Configur nginx php.conf
  template:
    src: php.conf.jinja2
    dest: /etc/nginx/extra/php.conf
  when: php_run_server.stdout == "nginx"
  
- name: Configur apache php.conf
  template:
    src: php.conf.jinja2
    dest: /etc/httpd/conf.d/php.conf
  when: php_run_server.stdout == "apache"

- debug: var=php_run_servername

- name: Configure PHP-FPM
  template:
    src: www.conf.jinja2
    dest: /etc/php-fpm.d/www.conf
  when: php_run_server.stdout != "nothing"
