- name: Test nginx server is running
  shell: |
    temp=`systemctl status nginx  | grep Active | grep running`
    [[ $temp ]] && php_run_server="nginx"
    echo $php_run_server
  register: php_run_server

- debug: var=php_run_server

- name: Configur php.conf
  template:
    src: php.conf.jinja2
    dest: /etc/nginx/extra/php.conf
  when: php_run_server.stdout == "nginx"

- name: Test apache server is running
  shell: |
    temp=`systemctl status httpd  |grep Active`
    [[ $temp =~ "running" ]] && php_run_server="apache"
    
- name: Configur php.conf
  template:
    src: php.conf.jinja2
    dest: /etc/httpd/conf.d/php.conf
  when: php_run_server == "apache"

# runtime sever is nginx,apache,or no sever is running
- name: Configure PHP-FPM
  template:
    src: www.conf.jinja2
    dest: /etc/php-fpm.d/www.conf
  when: php_run_server is defined and php_run_server is not none
