- name: Server set init value
  set_fact:
    php_run_server: ""
    
- name: Test nginx server is running
  shell: |
    temp=`systemctl status nginx  |grep Active`
    [[ $temp =~ "running" ]] && php_run_server="nginx"

- name: Configure php.conf
  copy:
    src: php.conf.jinja2
    dest: /etc/nginx/extra/php.conf
  when: php_run_server == "nginx"

- name: Test apache server is running
  shell: |
    temp=`systemctl status httpd  |grep Active`
    [[ $temp =~ "running" ]] && php_run_server="apache"
    
- name: Configure php.conf
  copy:
    src: php.conf.jinja2
    dest: /etc/httpd/conf.d/php.conf
  when: php_run_server == "apache"

# runtime sever is nginx,apache,or no sever is running
- name: Configure PHP-FPM
  template:
    src: www.conf.jinja2
    dest: /etc/php-fpm.d/www.conf
  when: php_run_server is defined and php_run_server is not none
