- name:  get the running server | apche | nginx |nothing
  shell: |
    if [ `ps -ef | grep nginx | grep -v grep | wc -l` -gt 0 ];then
    php_run_server=nginx
    elif [ `ps -ef | grep apache | grep -v grep | wc -l` -gt 0 ];then
    php_run_server=apache
    else
    php_run_server=nothing
    fi
    echo $php_run_server
  register: php_run_server
  
- name: set rphp_run_servername by running server
  set_fact: php_run_servername={{php_run_server.stdout}}

- debug: var=php_run_server.stdout

- name: Configure nginx php.conf
  template:
    src: php.conf.jinja2
    dest: /etc/nginx/extra/php.conf
  when: php_run_servername == "nginx"
  
- name: Configure apache php.conf
  template:
    src: php.conf.jinja2
    dest: /etc/httpd/conf.d/php.conf
  backup: yes
  when: php_run_servername == "apache" and ansible_os_family == "RedHat"

- name: Configure PHP-FPM of {{ansible_os_family}}
  template:
    src: www.conf.jinja2
    dest: /etc/php-fpm.d/www.conf
  when: php_run_servername != "nothing" and ansible_os_family == "RedHat"

- name: Configure PHP-FPM of {{ansible_os_family}}
  template:
    src: www.conf.jinja2
    dest: /etc/php/{{php_version}}/fpm/pool.d/www.conf
  when: php_run_servername != "nothing" and ansible_os_family == "Debian"
