- name: Import PHP PPA
  apt_repository:
    repo: ppa:ondrej/php

- name: Install PHP{{php_version}}
  apt:
    name: php{{php_version}}
    state: latest
    update_cache: yes
    
- name: Install php_modules_common for {{ansible_distribution}}, print when all module installation errors but installation go on
  apt: 
    name: "{{ item }}{{php_version}}"
    state: latest
    update_cache: yes
  register: php_install_result
  failed_when: False
  loop: "{{ php_modules_common }}"

- debug: 
    msg: "{{ php_install_result | json_query('results[*].results[*]') }}"

- name: Install php_extra_modules_ubuntu for {{ansible_distribution}}
  apt: 
    name: "{{ item }}"
    state: latest 
    update_cache: yes
  loop: "{{ php_extra_modules_ubuntu }}"

- name: Create a PHP  symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: '/etc/php/{{php_version}}/fpm/php.ini',dest: /data/config/php/php.ini}
    - {src: '/etc/php/{{php_version}}/fpm/php-fpm.conf',dest: /data/config/php/php-fpm.conf}
    - {src: '/var/log/php{{php_version}}-fpm.log',dest: '/data/logs/php{{php_version}}-fpm.log'}
    - {src: '/lib/systemd/system/php{{php_version}}-fpm.service',dest: /lib/systemd/system/php-fpm.service}
    - {src: '/etc/php/{{php_version}}/fpm/php.ini',dest: /etc/php.ini}
