- import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- name: Check PHP Version
  shell: php -v
  register: php_ver
  notify: PHP Version