#1 Prepare
- name: Create /data/config/php directory
  file:
    path: /data/config/php
    state: directory
    recurse: yes
    
#2 Install
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"
  
# Configure


# Verify 
- name: Check PHP Version
  shell: sudo sh -c "php -v | grep PHP | sed -n 1p 1>> /data/logs/install_version.txt"
  
- name: Check php-fpm Service
  shell: systemctl status php-fpm | grep Active*
  register: check_phpfpm_service
  notify: check_phpfpm_service
