- name: Import Remi's RPM PHP repository on {{ansible_distribution}}
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-{{ansible_distribution_major_version}}.rpm
  when: ansible_distribution == "CentOS"
  
- name: Import Remi's RPM PHP repository on AmazonLinux2
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
  when: ansible_distribution == "Amazon"  
    
- name: String convert, e.g 7.2 to 72
  set_fact:
    php_version_regex: "{{ php_version | regex_replace('^(?P<before>.+).(?P<after>\\d+)$', '\\g<before>\\g<after>')}}"
    
- name: Enable php verion for {{php_version}}
  shell: yum-config-manager --enable remi-php{{php_version_regex}}
  
- name: Install PHP core for {{ansible_distribution}}
  yum: 
    name: php
    update_cache: yes
  when: ansible_distribution == "CentOS"
  
- name: Install PHP core for {{ansible_distribution}}
  yum: 
    name: php
    disablerepo: amzn2-core
    update_cache: yes
  when: ansible_distribution == "Amazon"

- name: Install PHP extension packages for {{ansible_distribution}}
  yum: 
    name: "{{ item }}"
    state: present
    skip_broken: yes
  loop: "{{ php_packages_common }}"
  ignore_errors: yes
  
- name: Install extra PHP extension packages for {{ansible_distribution}}
  yum: 
    name: "{{ item }}"
    state: present
    skip_broken: yes
  loop: "{{ php_extra_packages_centos }}"
  ignore_errors: yes

- name: Install Composer
  get_url:
    url: "{{ php_getcomposer_url }}"
    dest: /usr/bin/composer
    mode: 0750

- block:
  - name: Download ioncube and unzip
    unarchive:
        src: https://dl.cnezsoft.com/ioncube_loaders_lin_x86-64.zip
        dest: /tmp/
        remote_src: yes 
  
  - name: copy ioncube module
    command: cp /tmp/ioncube/ioncube_loader_lin_{{php_version}}.so /usr/lib64/php/modules/

  - name: Write ioncube Configure
    shell: echo "zend_extension = /usr/lib64/php/modules/ioncube_loader_lin_{{php_version}}.so" >> /etc/php.ini
  when: php_ioncube 

- name: Create a PHP  symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: '/etc/php.ini',dest: /data/config/php/php.ini}  
    - {src: '/etc/php-fpm.d/www.conf',dest: /data/config/php/php-fpm.conf} 
    - {src: '/var/log/php-fpm',dest: '/data/logs/php-fpm'}
